name: Release notes generator
description: This Github action <strong>automatically creates a release notes</strong> when a milestone is closed.
runs:
  using: 'docker'
  image: 'docker://ghcr.io/step-security/release-notes-generator-action:v3.2.3@sha256:a5a096c764aa9fc943e96b449f8e672d4ec2cee4f7b791462fbb3040864fed90' #v3.2.3
branding:
  icon: tag
  color: blue
